/*
 * ISO_639_1.as
 * This file is part of Actionscript GNU Gettext
 *
 * Copyright (C) 2009 - Vincent Petithory
 *
 * Actionscript GNU Gettext is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * Actionscript GNU Gettext is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Actionscript GNU Gettext; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin St, Fifth Floor, 
 * Boston, MA  02110-1301  USA
 */
package gnu.as3.gettext 
{
	
    public const ISO_639_1:Object = {
		'aa'  :  'Afar. ',
		'ab'  :  'Abkhazian',
		'ad'  :  'Adangme',
		'ae'  :  'Avestan',
		'af'  :  'Afrikaans',
		'ak'  :  'Akan',
		'am'  :  'Amharic',
		'an'  :  'Aragonese',
		'ar'  :  'Arabic',
		'as'  :  'Assamese',
		'av'  :  'Avaric',
		'ay'  :  'Aymara',
		'az'  :  'Azerbaijani',
		'ba'  :  'Bashkir',
		'be'  :  'Byelorussian; Belarusian',
		'bg'  :  'Bulgarian',
		'bh'  :  'Bihari',
		'bi'  :  'Bislama',
		'bm'  :  'Bambara',
		'bn'  :  'Bengali; Bangla',
		'bo'  :  'Tibetan',
		'br'  :  'Breton',
		'bs'  :  'Bosnian',
		'ca'  :  'Catalan',
		'ce'  :  'Chechen',
		'ch'  :  'Chamorro',
		'co'  :  'Corsican',
		'cr'  :  'Cree',
		'cs'  :  'Czech',
		'cu'  :  'Church Slavic',
		'cv'  :  'Chuvash',
		'cy'  :  'Welsh',
		'da'  :  'Danish',
		'de'  :  'German',
		'dv'  :  'Divehi; Maldivian',
		'dz'  :  'Dzongkha; Bhutani',
		'ee'  :  'Éwé',
		'el'  :  'Greek',
		'en'  :  'English',
		'eo'  :  'Esperanto',
		'es'  :  'Spanish',
		'et'  :  'Estonian',
		'eu'  :  'Basque',
		'fa'  :  'Persian',
		'ff'  :  'Fulah',
		'fi'  :  'Finnish',
		'fj'  :  'Fijian; Fiji',
		'fo'  :  'Faroese',
		'fr'  :  'French',
		'fy'  :  'Western Frisian',
		'ga'  :  'Irish',
		'gd'  :  'Scots; Gaelic',
		'gl'  :  'Galician',
		'gn'  :  'Guarani',
		'gu'  :  'Gujarati',
		'gv'  :  'Manx',
		'ha'  :  'Hausa',
		'he'  :  'Hebrew (formerly iw)',
		'hi'  :  'Hindi',
		'ho'  :  'Hiri Motu',
		'hr'  :  'Croatian',
		'ht'  :  'Haitian; Haitian Creole',
		'hu'  :  'Hungarian',
		'hy'  :  'Armenian',
		'hz'  :  'Herero',
		'ia'  :  'Interlingua',
		'id'  :  'Indonesian (formerly in)',
		'ie'  :  'Interlingue',
		'ig'  :  'Igbo',
		'ik'  :  'Inupiak; Inupiaq',
		'io'  :  'Ido',
		'is'  :  'Icelandic',
		'it'  :  'Italian',
		'iu'  :  'Inuktitut',
		'ja'  :  'Japanese',
		'jv'  :  'Javanese',
		'ka'  :  'Georgian',
		'kg'  :  'Kongo',
		'ki'  :  'Kikuyu; Gikuyu',
		'kj'  :  'Kuanyama; Kwanyama',
		'kk'  :  'Kazakh',
		'kl'  :  'Kalaallisut; Greenlandic',
		'km'  :  'Khmer; Cambodian',
		'kn'  :  'Kannada',
		'ko'  :  'Korean',
		'ks'  :  'Kashmiri',
		'ku'  :  'Kurdish',
		'kv'  :  'Komi',
		'kw'  :  'Cornish',
		'ky'  :  'Kirghiz',
		'la'  :  'Latin',
		'lb'  :  'Letzeburgesch; Luxembourgish',
		'lg'  :  'Ganda',
		'li'  :  'Limburgish; Limburger; Limburgan',
		'ln'  :  'Lingala',
		'lo'  :  'Lao; Laotian',
		'lt'  :  'Lithuanian',
		'lu'  :  'Luba-Katanga',
		'lv'  :  'Latvian; Lettish',
		'mg'  :  'Malagasy',
		'mh'  :  'Marshallese',
		'mi'  :  'Maori',
		'mk'  :  'Macedonian',
		'ml'  :  'Malayalam',
		'mn'  :  'Mongolian',
		'mo'  :  'Moldavian',
		'mr'  :  'Marathi',
		'ms'  :  'Malay',
		'mt'  :  'Maltese',
		'my'  :  'Burmese',
		'na'  :  'Nauru',
		'nb'  :  'Norwegian Bokmål',
		'nd'  :  'Ndebele, North',
		'ne'  :  'Nepali',
		'ng'  :  'Ndonga',
		'nl'  :  'Dutch',
		'nn'  :  'Norwegian Nynorsk',
		'no'  :  'Norwegian',
		'nr'  :  'Ndebele, South',
		'nv'  :  'Navajo; Navaho',
		'ny'  :  'Chichewa; Nyanja',
		'oc'  :  'Occitan; Provençal',
		'om'  :  '(Afan) Oromo',
		'or'  :  'Oriya',
		'os'  :  'Ossetian; Ossetic',
		'pa'  :  'Panjabi; Punjabi',
		'pi'  :  'Pali',
		'pl'  :  'Polish',
		'ps'  :  'Pashto; Pushto',
		'pt'  :  'Portuguese',
		'qu'  :  'Quechua',
		'rm'  :  'Rhaeto-Romance',
		'rn'  :  'Rundi; Kirundi',
		'ro'  :  'Romanian',
		'ru'  :  'Russian',
		'rw'  :  'Kinyarwanda',
		'sa'  :  'Sanskrit',
		'sc'  :  'Sardinian',
		'sd'  :  'Sindhi',
		'se'  :  'Northern Sami',
		'sg'  :  'Sango; Sangro',
		'si'  :  'Sinhala; Sinhalese',
		'sk'  :  'Slovak',
		'sl'  :  'Slovenian',
		'sm'  :  'Samoan',
		'sn'  :  'Shona',
		'so'  :  'Somali',
		'sq'  :  'Albanian',
		'sr'  :  'Serbian',
		'ss'  :  'Swati; Siswati',
		'st'  :  'Sesotho; Sotho, Southern',
		'su'  :  'Sundanese',
		'sv'  :  'Swedish',
		'sw'  :  'Swahili',
		'ta'  :  'Tamil',
		'te'  :  'Telugu',
		'tg'  :  'Tajik',
		'th'  :  'Thai',
		'ti'  :  'Tigrinya',
		'tk'  :  'Turkmen',
		'tl'  :  'Tagalog',
		'tn'  :  'Tswana; Setswana',
		'to'  :  'Tonga',
		'tr'  :  'Turkish',
		'ts'  :  'Tsonga',
		'tt'  :  'Tatar',
		'tw'  :  'Twi',
		'ty'  :  'Tahitian',
		'ug'  :  'Uighur',
		'uk'  :  'Ukrainian',
		'ur'  :  'Urdu',
		'uz'  :  'Uzbek',
		'vi'  :  'Vietnamese',
		'vo'  :  'Volapük; Volapuk',
		'wa'  :  'Walloon',
		'wo'  :  'Wolof',
		'xh'  :  'Xhosa',
		'yi'  :  'Yiddish (formerly ji)',
		'yo'  :  'Yoruba',
		'za'  :  'Zhuang',
		'zh'  :  'Chinese',
		'zu'  :  'Zulu'
	}
	
}