/*
 * ISO_3166.as
 * This file is part of Actionscript GNU Gettext
 *
 * Copyright (C) 2009 - Vincent Petithory
 *
 * Actionscript GNU Gettext is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License', or
 * (at your option) any later version.
 *
 * Actionscript GNU Gettext is distributed in the hope that it will be useful',
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Actionscript GNU Gettext; if not', write to the Free Software
 * Foundation', Inc.', 51 Franklin St', Fifth Floor', 
 * Boston', MA  02110-1301  USA
 */
package gnu.as3.gettext 
{
	
    public const ISO_3166:Object = {
		'AD'  :  'Andorra', 
		'AE'  :  'United Arab Emirates', 
		'AF'  :  'Afghanistan', 
		'AG'  :  'Antigua and Barbuda', 
		'AI'  :  'Anguilla', 
		'AL'  :  'Albania', 
		'AM'  :  'Armenia', 
		'AN'  :  'Netherlands Antilles', 
		'AO'  :  'Angola', 
		'AQ'  :  'Antarctica', 
		'AR'  :  'Argentina', 
		'AS'  :  'Samoa (American)', 
		'AT'  :  'Austria', 
		'AU'  :  'Australia', 
		'AW'  :  'Aruba', 
		'AX'  :  'Aaland Islands', 
		'AZ'  :  'Azerbaijan', 
		'BA'  :  'Bosnia and Herzegovina', 
		'BB'  :  'Barbados', 
		'BD'  :  'Bangladesh', 
		'BE'  :  'Belgium', 
		'BF'  :  'Burkina Faso', 
		'BG'  :  'Bulgaria', 
		'BH'  :  'Bahrain', 
		'BI'  :  'Burundi', 
		'BJ'  :  'Benin', 
		'BM'  :  'Bermuda', 
		'BN'  :  'Brunei', 
		'BO'  :  'Bolivia', 
		'BR'  :  'Brazil', 
		'BS'  :  'Bahamas', 
		'BT'  :  'Bhutan', 
		'BV'  :  'Bouvet Island', 
		'BW'  :  'Botswana', 
		'BY'  :  'Belarus', 
		'BZ'  :  'Belize', 
		'CA'  :  'Canada', 
		'CC'  :  'Cocos (Keeling) Islands', 
		'CD'  :  'Congo (Dem. Rep.)', 
		'CF'  :  'Central African Republic', 
		'CG'  :  'Congo (Rep.)', 
		'CH'  :  'Switzerland', 
		'CI'  :  'Côte d\'Ivoire', 
		'CK'  :  'Cook Islands', 
		'CL'  :  'Chile', 
		'CM'  :  'Cameroon', 
		'CN'  :  'China', 
		'CO'  :  'Colombia', 
		'CR'  :  'Costa Rica', 
		'CU'  :  'Cuba', 
		'CV'  :  'Cape Verde', 
		'CX'  :  'Christmas Island', 
		'CY'  :  'Cyprus', 
		'CZ'  :  'Czech Republic', 
		'DE'  :  'Germany', 
		'DJ'  :  'Djibouti', 
		'DK'  :  'Denmark', 
		'DM'  :  'Dominica', 
		'DO'  :  'Dominican Republic', 
		'DZ'  :  'Algeria', 
		'EC'  :  'Ecuador', 
		'EE'  :  'Estonia', 
		'EG'  :  'Egypt', 
		'EH'  :  'Western Sahara', 
		'ER'  :  'Eritrea', 
		'ES'  :  'Spain', 
		'ET'  :  'Ethiopia', 
		'FI'  :  'Finland', 
		'FJ'  :  'Fiji', 
		'FK'  :  'Falkland Islands', 
		'FM'  :  'Micronesia', 
		'FO'  :  'Faeroe Islands', 
		'FR'  :  'France', 
		'GA'  :  'Gabon', 
		'GB'  :  'Britain (United Kingdom)', 
		'GD'  :  'Grenada', 
		'GE'  :  'Georgia', 
		'GF'  :  'French Guiana', 
		'GG'  :  'Guernsey', 
		'GH'  :  'Ghana', 
		'GI'  :  'Gibraltar', 
		'GL'  :  'Greenland', 
		'GM'  :  'Gambia', 
		'GN'  :  'Guinea', 
		'GP'  :  'Guadeloupe', 
		'GQ'  :  'Equatorial Guinea', 
		'GR'  :  'Greece', 
		'GS'  :  'South Georgia and the South Sandwich Islands', 
		'GT'  :  'Guatemala', 
		'GU'  :  'Guam', 
		'GW'  :  'Guinea-Bissau', 
		'GY'  :  'Guyana', 
		'HK'  :  'Hong Kong', 
		'HM'  :  'Heard Island and McDonald Islands', 
		'HN'  :  'Honduras', 
		'HR'  :  'Croatia', 
		'HT'  :  'Haiti', 
		'HU'  :  'Hungary', 
		'ID'  :  'Indonesia', 
		'IE'  :  'Ireland', 
		'IL'  :  'Israel', 
		'IM'  :  'Isle of Man', 
		'IN'  :  'India', 
		'IO'  :  'British Indian Ocean Territory', 
		'IQ'  :  'Iraq', 
		'IR'  :  'Iran', 
		'IS'  :  'Iceland', 
		'IT'  :  'Italy', 
		'JE'  :  'Jersey', 
		'JM'  :  'Jamaica', 
		'JO'  :  'Jordan', 
		'JP'  :  'Japan', 
		'KE'  :  'Kenya', 
		'KG'  :  'Kyrgyzstan', 
		'KH'  :  'Cambodia', 
		'KI'  :  'Kiribati', 
		'KM'  :  'Comoros', 
		'KN'  :  'St Kitts and Nevis', 
		'KP'  :  'Korea (North)', 
		'KR'  :  'Korea (South)', 
		'KW'  :  'Kuwait', 
		'KY'  :  'Cayman Islands', 
		'KZ'  :  'Kazakhstan', 
		'LA'  :  'Laos', 
		'LB'  :  'Lebanon', 
		'LC'  :  'St Lucia', 
		'LI'  :  'Liechtenstein', 
		'LK'  :  'Sri Lanka', 
		'LR'  :  'Liberia', 
		'LS'  :  'Lesotho', 
		'LT'  :  'Lithuania', 
		'LU'  :  'Luxembourg', 
		'LV'  :  'Latvia', 
		'LY'  :  'Libya', 
		'MA'  :  'Morocco', 
		'MC'  :  'Monaco', 
		'MD'  :  'Moldova', 
		'ME'  :  'Montenegro', 
		'MG'  :  'Madagascar', 
		'MH'  :  'Marshall Islands', 
		'MK'  :  'Macedonia', 
		'ML'  :  'Mali', 
		'MM'  :  'Myanmar (Burma)', 
		'MN'  :  'Mongolia', 
		'MO'  :  'Macao', 
		'MP'  :  'Northern Mariana Islands', 
		'MQ'  :  'Martinique', 
		'MR'  :  'Mauritania', 
		'MS'  :  'Montserrat', 
		'MT'  :  'Malta', 
		'MU'  :  'Mauritius', 
		'MV'  :  'Maldives', 
		'MW'  :  'Malawi', 
		'MX'  :  'Mexico', 
		'MY'  :  'Malaysia', 
		'MZ'  :  'Mozambique', 
		'NA'  :  'Namibia', 
		'NC'  :  'New Caledonia', 
		'NE'  :  'Niger', 
		'NF'  :  'Norfolk Island', 
		'NG'  :  'Nigeria', 
		'NI'  :  'Nicaragua', 
		'NL'  :  'Netherlands', 
		'NO'  :  'Norway', 
		'NP'  :  'Nepal', 
		'NR'  :  'Nauru', 
		'NU'  :  'Niue', 
		'NZ'  :  'New Zealand', 
		'OM'  :  'Oman', 
		'PA'  :  'Panama', 
		'PE'  :  'Peru', 
		'PF'  :  'French Polynesia', 
		'PG'  :  'Papua New Guinea', 
		'PH'  :  'Philippines', 
		'PK'  :  'Pakistan', 
		'PL'  :  'Poland', 
		'PM'  :  'St Pierre and Miquelon', 
		'PN'  :  'Pitcairn', 
		'PR'  :  'Puerto Rico', 
		'PS'  :  'Palestine', 
		'PT'  :  'Portugal', 
		'PW'  :  'Palau', 
		'PY'  :  'Paraguay', 
		'QA'  :  'Qatar', 
		'RE'  :  'Reunion', 
		'RO'  :  'Romania', 
		'RS'  :  'Serbia', 
		'RU'  :  'Russia', 
		'RW'  :  'Rwanda', 
		'SA'  :  'Saudi Arabia', 
		'SB'  :  'Solomon Islands', 
		'SC'  :  'Seychelles', 
		'SD'  :  'Sudan', 
		'SE'  :  'Sweden', 
		'SG'  :  'Singapore', 
		'SH'  :  'St Helena', 
		'SI'  :  'Slovenia', 
		'SJ'  :  'Svalbard and Jan Mayen', 
		'SK'  :  'Slovakia', 
		'SL'  :  'Sierra Leone', 
		'SM'  :  'San Marino', 
		'SN'  :  'Senegal', 
		'SO'  :  'Somalia', 
		'SR'  :  'Suriname', 
		'ST'  :  'Sao Tome and Principe', 
		'SV'  :  'El Salvador', 
		'SY'  :  'Syria', 
		'SZ'  :  'Swaziland', 
		'TC'  :  'Turks and Caicos Islands', 
		'TD'  :  'Chad', 
		'TF'  :  'French Southern and Antarctic Lands', 
		'TG'  :  'Togo', 
		'TH'  :  'Thailand', 
		'TJ'  :  'Tajikistan', 
		'TK'  :  'Tokelau', 
		'TL'  :  'Timor-Leste', 
		'TM'  :  'Turkmenistan', 
		'TN'  :  'Tunisia', 
		'TO'  :  'Tonga', 
		'TR'  :  'Turkey', 
		'TT'  :  'Trinidad and Tobago', 
		'TV'  :  'Tuvalu', 
		'TW'  :  'Taiwan', 
		'TZ'  :  'Tanzania', 
		'UA'  :  'Ukraine', 
		'UG'  :  'Uganda', 
		'UM'  :  'US minor outlying islands', 
		'US'  :  'United States', 
		'UY'  :  'Uruguay', 
		'UZ'  :  'Uzbekistan', 
		'VA'  :  'Vatican City', 
		'VC'  :  'St Vincent and the Grenadines', 
		'VE'  :  'Venezuela', 
		'VG'  :  'Virgin Islands (UK)', 
		'VI'  :  'Virgin Islands (US)', 
		'VN'  :  'Vietnam', 
		'VU'  :  'Vanuatu', 
		'WF'  :  'Wallis and Futuna', 
		'WS'  :  'Samoa (Western)', 
		'YE'  :  'Yemen', 
		'YT'  :  'Mayotte', 
		'ZA'  :  'South Africa', 
		'ZM'  :  'Zambia', 
		'ZW'  :  'Zimbabwe'
	}
}
